name: Vietnam_economic_lakehouse
version: '1.0.0'
config-version: 2

profile: Vietnam_economic_lakehouse

model-paths: ["models"]
macro-paths: ["macros"]

models:
  Vietnam_economic_lakehouse:
    staging:
      +materialized: view
      +schema: staging

    dimensions:
      +materialized: delta_table
      +schema: gold


    
    facts:
      +materialized: delta_table
      +schema: gold


    marts:
      +materialized: table
      +schema: marts
      +file_format: delta
      +pre-hook: "DROP TABLE IF EXISTS {{ this }}"